version: 2.1

executors:
  helm-kubectl:
    docker:
    - image: dtzar/helm-kubectl

jobs:
  package-and-upload:
    executor: helm-kubectl
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - "1f:8c:ee:23:ca:1e:b1:ac:5b:05:17:4e:ef:00:78:11"
      - run:
          name: key-scan
          command: ssh-keyscan github.com >> ~/.ssh/known_hosts
      - run:
          name: git clone charts
          command: git clone git@github.com:DAXGRID/charts.git
      - run:
          name: git clone tippecanoe-chart
          command: git clone git@github.com:DAXGRID/tippecanoe-chart.git
      - run:
          name: package and push
          command: |
             cd ./charts
             helm package ../tippecanoe-chart/tippecanoe
             helm repo index ./ --url https://daxgrid.github.io/charts/
             git config user.email "admin@dax.dk"
             git config user.name "dax-bot"
             git add .
             git commit -m "adds/updates tippecanoe-chart - $(date --utc)"
             git push
workflows:
  package-and-upload-chart:
    jobs:
      - package-and-upload:
          filters:
            branches:
              only:
                - master