image:
  repository: openftth/tippecanoe
  tag: v1.36.0

schedule: "0 0 * * *"

commandArgs:
  - "tippecanoe"

restartPolicy: Never
backoffLimit: 0

storage:
  enabled: false
  size: 1Gi
  className: ""
  path: "/data"

gdal:
  enabled: false
  image:
    repository: osgeo/gdal
    tag: alpine-small-latest
    commandArgs:
    - "ogr2ogr"